Repository avincodes/Web-dev-Snippets, pull requests merged in 2022-10, with the labels that each got.

#30 Added a e-commerce website
  e-commerce website/README.md
  e-commerce website/css/index.css
  e-commerce website/images/camera.jpg
  e-commerce website/images/intro-bg_1.jpg
  e-commerce website/images/shirt.jpg
  e-commerce website/images/watch.jpg
  e-commerce website/index.html
Labels: question, hacktobefest-approved

#29 react to do list
  react-to-do-list-master/LICENSE
  react-to-do-list-master/README.md
  react-to-do-list-master/package.json
  react-to-do-list-master/public/favicon.ico
  react-to-do-list-master/public/index.html
  react-to-do-list-master/public/manifest.json
  react-to-do-list-master/src/App.css
  react-to-do-list-master/src/App.js
  react-to-do-list-master/src/App.test.js
  react-to-do-list-master/src/ColumnList.css
  react-to-do-list-master/src/ColumnList.js
  react-to-do-list-master/src/ConfirmDialog.js
  react-to-do-list-master/src/If.js
  react-to-do-list-master/src/MobileTearSheet.js
  react-to-do-list-master/src/index.css
  react-to-do-list-master/src/index.js
  react-to-do-list-master/src/logo.svg
  react-to-do-list-master/src/registerServiceWorker.js
Labels: elaboration-requested

#41 Added Contributors Profile | Fixes #40
  README.md
Labels: hacktobefest-approved, hacktoberfest

#43 CSSglowingbutton/zareenf01
  CSS Glowing Button
  CSSglowingbutton/README.md
  CSSglowingbutton/button.html
  CSSglowingbutton/img.png
Labels: hacktobefest-approved, hacktoberfest

#44 Created the web terminal
  Web-terminal/README.md
  Web-terminal/images/screenshot.png
  Web-terminal/images/screenshot2.png
  Web-terminal/index.css
  Web-terminal/index.html
  Web-terminal/script.js
Labels: hacktobefest-approved, hacktoberfest

#46 Added Live weather Web Page
  Live-Weather/Cloud.jpg
  Live-Weather/Haze.png
  Live-Weather/Rain.png
  Live-Weather/Readme.md
  Live-Weather/Snow.png
  Live-Weather/Sunny.png
  Live-Weather/Thunder.png
  Live-Weather/front.png
  Live-Weather/weather.css
  Live-Weather/weather.html
  Live-Weather/weather.jsx
Labels: hacktobefest-approved, hacktoberfest

#48 Added my react app for search table.
  .idea/.gitignore
  .idea/Web-dev-Snippets.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  react-table-search/Demo/image_1.png
  react-table-search/Demo/image_2.png
  react-table-search/Demo/image_3.png
  react-table-search/README.md
  react-table-search/frontend/.gitignore
  react-table-search/frontend/README.md
  react-table-search/frontend/package-lock.json
  react-table-search/frontend/package.json
  react-table-search/frontend/public/favicon.ico
  react-table-search/frontend/public/index.html
  react-table-search/frontend/public/logo192.png
  react-table-search/frontend/public/logo512.png
  react-table-search/frontend/public/manifest.json
  react-table-search/frontend/public/robots.txt
  react-table-search/frontend/src/App.css
  react-table-search/frontend/src/App.js
  react-table-search/frontend/src/App.test.js
  react-table-search/frontend/src/Search.js
  react-table-search/frontend/src/Title.js
  react-table-search/frontend/src/index.css
  react-table-search/frontend/src/index.js
  react-table-search/frontend/src/logo.svg
  react-table-search/frontend/src/reportWebVitals.js
  react-table-search/frontend/src/setupTests.js
Labels: hacktobefest-approved, hacktoberfest

#51 Animated button
  CSS button with ring indicator/README.md
  CSS button with ring indicator/index.html
  CSS button with ring indicator/style.css
  Profile Card/images/ayu.jpg
  Profile Card/index.html
  Profile Card/script.js
  Profile Card/style.css
Labels: hacktobefest-approved, hacktoberfest

#55 Add card css snippet
  css-card-with-button/README.md
  css-card-with-button/index.html
  css-card-with-button/screenshot.png
  css-card-with-button/style.css
Labels: hacktobefest-approved, hacktoberfest

#53 Progress Bar Added
  Readme.md
  Skills bar/index.html
  Skills bar/style.css
Labels: hacktobefest-approved, hacktoberfest

#63 Created contributors.md
  contirbutors.md
Labels: hacktobefest-approved, hacktoberfest

#66 Update contirbutors.md
  contirbutors.md
Labels: hacktobefest-approved, hacktoberfest

#67 Corrected Typo!
  contributors.md
Labels: hacktobefest-approved, hacktoberfest

#62 Product Card Added
  Product Card/01.jpg
  Product Card/index.html
  Product Card/style.css
Labels: hacktobefest-approved, hacktoberfest

#73 Added FAQ-website
  FAQ-website/Open.png
  FAQ-website/README.md
  FAQ-website/bg.jpg
  FAQ-website/home.png
  FAQ-website/index.html
  FAQ-website/style.css
Labels: hacktobefest-approved, hacktoberfest

#77 Added the first steps of Contributing.
  contributors.md
Labels: hacktobefest-approved, hacktoberfest

#78 Completed Contributors.md
  contributors.md
Labels: hacktobefest-approved, hacktoberfest

#83 Update contributors.md
  contributors.md
Labels: hacktobefest-approved, hacktoberfest
